version: "3.8"

services:
  mysql:
    image: mysql:8
    container_name: mysql_db_docker
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rudra@root
      MYSQL_DATABASE: quantitymeasurementdb
    volumes:
      - ./mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: rudra@root
    depends_on:
      - mysql

  springboot:
    build: .
    container_name: qma-springboot-project
    restart: always
    ports:
      - "8080:8080"
    environment:
      SERVER_PORT: 8080
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DB: quantitymeasurementdb
      MYSQL_USER: root
      MYSQL_PASSWORD: rudra@root
      APP_BASE_URL: http://localhost:8080
      JWT_SECRET: YourSuperSecretKeyThatIsAtLeast256BitsLongForHS256Algorithm123456
      GOOGLE_CLIENT_ID: ""
      GOOGLE_CLIENT_SECRET: ""
    depends_on:
      - mysql