spring.application.name=quantity-measurement-app

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# H2 Console
spring.h2.console.settings.web-allow-others=false

# MySQL Database
spring.datasource.url=${MYSQL_URL:jdbc:mysql://localhost:3306/quantitymeasurementdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=${MYSQLUSER:root}
spring.datasource.password=${MYSQLPASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Connection Pool
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000

# MVC Error Handling
spring.mvc.problemdetails.enabled=true

# Logging
logging.level.root=INFO
logging.level.com.app.quantitymeasurementapp=DEBUG
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

# Swagger / OpenAPI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.try-it-out-enabled=true
springdoc.swagger-ui.operations-sorter=method

# Actuator
management.endpoints.web.exposure.include=health,info,metrics,env
management.endpoint.health.show-details=always
management.info.env.enabled=true

# App Info
info.app.name=Quantity Measurement App
info.app.version=1.0.0
info.app.description=UC18 Spring Boot REST + JPA + Spring Security

# Server
server.port=${PORT:8080}

# Google OAuth2
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,profile,email
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/google

# JWT
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}

#spring.profiles.active=local

# App URLs / CORS
app.base-url=${APP_BASE_URL:http://localhost:8080}
app.frontend-base-url=${FRONTEND_BASE_URL:http://localhost:4200}
app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:4200}